### ISSUE TITLE
Describe DateFnsProvider

### ISSUE THREAD

**Issue by simplenotezy** [jhannes/react-date-fns-hooks#3]
Would be nice to describe what `DateFnsProvider` - it's mentioned in the getting started, but with no description of what it is.

**Comment by jhannes** [comment]
Thanks for the input. Perhaps I should generate some documentation from the code :-)

**Comment by jhannes** [comment]
Here is a start: https://jhannes.github.io/react-date-fns-hooks/modules.html#DateFnsProvider

If you have input on what you'd like to know, I'd enjoy that. Otherwise, I'll try to come up with something good.

**Comment by simplenotezy** [comment]
Very cool! @jhannes
